import { PROCESSING_CEILING } from "../../shared/intakeCeiling";

export const PROCESSING_UNIT_USD = 0.01;
export const STANDARD_UNITS_PER_PAGE = 4;
export const MAX_UNITS_PER_PAGE = 6;
export const MAX_QUOTED_PAGES = 10_000;

export type CompileQuote = {
  pages: number;
  standardUnits: number;
  maximumUnits: number;
  estimatedUsd: number;
  maximumUsd: number;
};

/**
 * How a page count was arrived at, and therefore what may be said about it.
 *
 * There used to be a fourth basis: `ceil(bytes / 65,536)`, for a file whose format states no page
 * count. It was a defensible spend ceiling and a terrible fact -- derived from file size, with no
 * relationship to how many pages the document has -- and it was reaching the customer under the
 * heading "Pages", next to a dollar figure they were being asked to authorise. Labelling it an
 * estimate made the label honest and left the number invented, which this repository forbids
 * outright, so it is gone: a file nobody can count yet has no page number at all, and the
 * spreadsheet whose count it mostly served is now billed on the pages of the sanitized PDF,
 * counted after conversion.
 *
 * `provisional` therefore no longer describes a basis. It survives as the confidence of a set
 * with nothing counted in it, which is what `canReserveAgainst` has to refuse.
 *
 * "Read out of the document" is not one thing, and treating it as one is how a Word file's
 * stale metadata came to be shown as "Verified pages":
 *
 *   pdf_page_tree   the page tree, counted. The PDF has that many pages.
 *   image           one image is one page.
 *   pptx_slides     slide parts, counted, under a contract that bills a slide as a page.
 *   docx_declared   the number Word wrote into docProps/app.xml the last time it saved.
 *
 * The first three are measurements of the file. The fourth is a *claim by another program*
 * about a rendering that is not this one: a .docx has no pages in any structural sense --
 * pagination belongs to a renderer, with its fonts, its page size and its hyphenation. The
 * number is usually about right, which is why it is worth showing, and it is stale whenever
 * the file was edited by anything that did not update it, generated by a converter, or is
 * about to be rendered by something other than the Word that wrote it.
 *
 * So it is `declared`, not `verified`: good enough to quote and to reserve against, not good
 * enough to be the sentence "we counted this". A count becomes `verified` for a DOCX only
 * after the document has actually been rendered, which happens in processing, not preflight.
 */
export type PageEstimateBasis =
  | "pdf_page_tree"
  | "image"
  | "pptx_slides"
  | "docx_declared";
export type PageEstimateConfidence = "provisional" | "declared" | "verified";

export type PageEstimate = {
  pages: number;
  basis: PageEstimateBasis;
  confidence: PageEstimateConfidence;
};

export function pageEstimateConfidence(basis: PageEstimateBasis): PageEstimateConfidence {
  if (basis === "docx_declared") return "declared";
  return "verified";
}

/** The heading a page count is allowed to appear under, given how it was derived. */
export function pageCountLabel(confidence: PageEstimateConfidence) {
  if (confidence === "verified") return "Verified pages";
  if (confidence === "declared") return "Declared pages";
  return "Pages not counted yet";
}

/**
 * True when this count may back a final charge authorisation rather than a preview.
 *
 * A declared count may not. Settling against a number another program wrote about a rendering
 * nobody performed is charging for work that was not measured; settlement uses the pages the
 * pipeline actually produced.
 */
export function canAuthorizeCharge(estimate: PageEstimate) {
  return estimate.confidence === "verified";
}

/**
 * True when this count may back a reservation and the maximum shown to the customer.
 *
 * Weaker than settlement on purpose. A reservation is a ceiling being held, and a declared
 * count is a sound basis for one -- it is the customer's own file saying how long it is. What
 * it may not do is close the transaction.
 */
export function canReserveAgainst(estimate: PageEstimate) {
  return estimate.confidence !== "provisional";
}

/**
 * The confidence of a set is the weakest confidence in it.
 *
 * One file quoted from its size drags the whole preflight to an estimate, and one Word file
 * drags it to "declared", because the total the customer authorises against is then partly
 * that number.
 */
export function weakestConfidence(
  confidences: readonly PageEstimateConfidence[],
): PageEstimateConfidence {
  if (confidences.length === 0) return "provisional";
  if (confidences.includes("provisional")) return "provisional";
  if (confidences.includes("declared")) return "declared";
  return "verified";
}

export function quoteCompilePages(pages: number): CompileQuote | null {
  if (!Number.isSafeInteger(pages) || pages < 1 || pages > MAX_QUOTED_PAGES) return null;
  const standardUnits = pages * STANDARD_UNITS_PER_PAGE;
  const maximumUnits = pages * MAX_UNITS_PER_PAGE;
  return {
    pages,
    standardUnits,
    maximumUnits,
    estimatedUsd: standardUnits * PROCESSING_UNIT_USD,
    maximumUsd: maximumUnits * PROCESSING_UNIT_USD,
  };
}

export function formatUsd(value: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
}

export function estimateBillablePages(value: {
  bytes: number;
  mimeType: string;
  declaredPages?: number | null;
  /**
   * How `declaredPages` was arrived at, from `measurePages`.
   *
   * Absent, it falls back to `docx_declared` -- the weakest claim a real count can carry. A
   * caller that has not said where its number came from must not be able to obtain "Verified"
   * by omission, which is what the single `declared` basis used to grant everybody.
   */
  declaredBasis?: PageEstimateBasis | null;
}): PageEstimate | null {
  if (!Number.isSafeInteger(value.bytes) || value.bytes < 1) return null;
  if (value.declaredPages && Number.isSafeInteger(value.declaredPages)
    && value.declaredPages >= 1 && value.declaredPages <= MAX_QUOTED_PAGES) {
    const basis = value.declaredBasis ?? "docx_declared";
    return { pages: value.declaredPages, basis, confidence: pageEstimateConfidence(basis) };
  }
  if (value.mimeType.toLowerCase().startsWith("image/")) {
    return { pages: 1, basis: "image", confidence: "verified" };
  }
  // No count, and no invented one. A spreadsheet is counted on the sanitized PDF after
  // conversion; any other format that states no page count is counted when it is read. Callers
  // show the absence -- they never fill it in from the file size.
  return null;
}


/**
 * The pages to *reserve* for a source nobody has counted yet -- never a page count to show.
 *
 * `estimateBillablePages` returns `null` for a file whose format states no page count, which is
 * the correct answer to "how many pages is this" and a dangerous one to reserve against. Both
 * server call sites used to write `?? 1`: before the byte-derived fallback was removed they
 * reserved a byte-derived ceiling, and afterwards they reserved **one page** for a spreadsheet
 * that can settle at up to `PROCESSING_CEILING.maxSourcePages`. Bounded, because nothing in the
 * chain reads more than that ceiling and settlement bills the pages actually produced -- but the
 * gap between the hold and the settlement is credit an untruthful client can spend twice.
 *
 * So the fallback is the deployment's own documented page ceiling: the most a rasterizer will
 * ever render for one source, which is the most a settlement for one source can ever charge.
 * It over-reserves, deliberately and in the customer's favour on refusal, and it is never
 * rendered: `pageCountLabel("provisional")` is what a reader sees for an uncounted file, and it
 * says the pages are not counted yet. A number chosen to hold credit is not a fact about a
 * document, and this function returns the first and never the second.
 */
export function reservationPageCeiling(value: Parameters<typeof estimateBillablePages>[0]): number {
  return estimateBillablePages(value)?.pages ?? PROCESSING_CEILING.maxSourcePages;
}
