-- DRAFT owning regressions; PostgreSQL/pgTAP/FK/privileges/concurrency execution UNRUN.
-- Only a disposable OFFLINE Foundation database with exact canonical migrations + existing
-- job-authority draft + frozen purpose schema + corrected reader. No customer/provider I/O.
-- Public reader gate remains FALSE. Tests exercise a transaction-local pg_temp INVOKER copy
-- with gate true and a private after-waits hook; they never replace/activate the public reader.
-- Only UNREVIEWED/PROPOSED/UNBOUND synthetic native rows. Everything rolls back.
begin;
set local transaction isolation level read committed;
select no_plan();
select ok(pg_catalog.strpos(pg_catalog.pg_get_functiondef('public.read_foundation_native_purpose_candidate_v1(jsonb,uuid)'::regprocedure),
  'prerequisite_review_complete constant boolean := false')>0,'public prerequisite gate remains false');
select is(public.read_foundation_native_purpose_candidate_v1('{}',null),null::jsonb,'public runtime remains closed');

insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,
  raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values
 ('00000000-0000-0000-0000-000000000000','88888888-8888-4888-8888-888888888891','authenticated','authenticated',
  'native-candidate-member@example.invalid','$2a$10$fixture',now(),'{"provider":"email","providers":["email"]}','{}',now(),now()),
 ('00000000-0000-0000-0000-000000000000','99999999-9999-4999-8999-999999999992','authenticated','authenticated',
  'native-candidate-owner@example.invalid','$2a$10$fixture',now(),'{"provider":"email","providers":["email"]}','{}',now(),now());
insert into public.foundation_workspaces(workspace_key,display_name,created_by)
values('pilot-candidate','Synthetic candidate fixture','99999999-9999-4999-8999-999999999992');
insert into public.foundation_workspace_members(workspace_key,user_id,role,state,accepted_at)
values ('pilot-candidate','99999999-9999-4999-8999-999999999992','owner','active',now()),
 ('pilot-candidate','88888888-8888-4888-8888-888888888891','member','active',now());
-- Existing billing rows are inert REFERENCES, not new billing policy or a charge/hold RPC.
insert into public.foundation_billing_accounts(workspace_key,user_id)
values('pilot-candidate','88888888-8888-4888-8888-888888888891');
insert into public.foundation_intake_approvals(approval_id,workspace_key,user_id,attempt_key,
 client_manifest_digest,scope_digest,pricing_fingerprint,file_count,aggregate_maximum_pages,
 aggregate_reserved_credits,aggregate_maximum_credits,created_at,expires_at)
values('90000000-0000-4000-8000-000000000091','pilot-candidate','88888888-8888-4888-8888-888888888891',
 'native-candidate-test-attempt','sha256:'||repeat('a',64),'sha256:'||repeat('b',64),'sha256:'||repeat('c',64),
 2,2,4,4,now(),now()+interval '10 minutes');
create function pg_temp.candidate_doc(i integer) returns uuid language sql immutable as $$
 select ('20000000-0000-4000-8000-'||pg_catalog.lpad(i::text,12,'0'))::uuid;
$$;
create function pg_temp.candidate_rep(v text,k text,key text) returns text language sql immutable as $$
 select 'rep-'||pg_catalog.substr(pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(v||pg_catalog.chr(10)||k||pg_catalog.chr(10)||key,'UTF8')),'hex'),1,32);
$$;
insert into public.foundation_compile_jobs(job_id,workspace_key,created_by_user_id,authorization_revision,
 document_ids,idempotency_key,state,documents_total,collection_id,compilation_mode)
select 'cjob-'||repeat('4',32),'pilot-candidate','88888888-8888-4888-8888-888888888891',authorization_revision,
 array[pg_temp.candidate_doc(92)::text,pg_temp.candidate_doc(91)::text],repeat('4',64),'reading',2,null,'document_batch'
from public.foundation_workspace_members where workspace_key='pilot-candidate' and user_id='88888888-8888-4888-8888-888888888891';
insert into public.foundation_native_qualification_profiles(qualification_id,producer_id,producer_key_id,producer_key_reference,
 producer_revision,caller_id,reader_revision,input_mime_type,cir_schema_version,native_parser_version)
values('synthetic-unreviewed-correction','synthetic-producer','synthetic-key-ref','opaque-reference-never-loaded',
 'sha256:'||repeat('1',64),'synthetic-caller','sha256:'||repeat('2',64),
 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','cir-1.0.0','1.2.0');
-- Golden identities are generated by the existing nativeCollectionId/nativeReplayBinding
-- functions and recorded/checked by the focused offline harness; NOT job output collection_id.
insert into public.foundation_native_purpose_grants(native_grant_id,intake_approval_id,intake_scope_digest,qualification_id,
 workspace_key,tenant_id,principal_user_id,job_id,authorization_revision,collection_id,replay_binding)
select '90000000-0000-4000-8000-000000000092','90000000-0000-4000-8000-000000000091','sha256:'||repeat('b',64),
 'synthetic-unreviewed-correction',workspace_key,workspace_key,created_by_user_id,job_id,authorization_revision,
 'collection-785c3825ef186bf71c72c6aeb6a5078a','native-work-1fa26e9ef83fb26f16ead43f41a7df53'
from public.foundation_compile_jobs where job_id='cjob-'||repeat('4',32);
create function pg_temp.seed_candidate_member(i integer) returns void language plpgsql as $$
declare
 d uuid:=pg_temp.candidate_doc(i);v text;original_key text;pdf_key text;oid text;pid text;
 rid uuid:=('30000000-0000-4000-8000-'||pg_catalog.lpad(i::text,12,'0'))::uuid;
 mime constant text:='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
begin
 v:=d::text||':'||repeat('c',64);original_key:='quarantine/pilot-candidate/'||d::text||'/source';
 pdf_key:='immutable/pilot-candidate/pilot-candidate/'||d::text||'/'||repeat('d',64)||'/sanitized.pdf';
 oid:=pg_temp.candidate_rep(v,'original',original_key);pid:=pg_temp.candidate_rep(v,'normalized',pdf_key);
 insert into public.foundation_intake_approval_files(approval_id,file_key,document_id,content_sha256,byte_length,declared_mime_type,
  page_basis,approved_max_pages,approved_reserved_credits,approved_maximum_credits,created_at)
 values('90000000-0000-4000-8000-000000000091','synthetic-file-'||i,d,'sha256:'||repeat('c',64),12,mime,'measured',1,2,2,now());
 insert into public.foundation_compute_reservations(reservation_id,workspace_key,document_id,user_id,reserved_credits,maximum_credits,billing_source,expires_at)
 values(rid,'pilot-candidate',d,'88888888-8888-4888-8888-888888888891',2,2,'paid',now()+interval '10 minutes');
 update public.foundation_intake_approval_files set state='reserved',reservation_id=rid,reserved_at=now() where document_id=d;
 update public.foundation_intake_approval_files set state='confirmed',confirmed_at=now() where document_id=d;
 insert into public.foundation_intake_admissions(workspace_key,document_id,user_id,object_key,requested_bytes,declared_mime_type,
  expires_at,confirmed_at,source_sha256,state)
 values('pilot-candidate',d,'88888888-8888-4888-8888-888888888891',original_key,12,mime,now()+interval '10 minutes',now(),'sha256:'||repeat('c',64),'quarantined');
 insert into public.sources(source_id,tenant_id,workspace_id,origin_kind,source_family,created_at,origin_provider)
 values(d::text,'pilot-candidate','pilot-candidate','upload','spreadsheet',now(),'synthetic-original');
 insert into public.source_versions(source_version_id,source_id,immutable_object_key,content_sha256,byte_length,mime_type,observed_at)
 values(v,d::text,original_key,'sha256:'||repeat('c',64),12,mime,now());
 insert into public.source_representations(representation_id,source_version_id,kind,provider_id,provider_revision,content_sha256,object_key,lossy,derived_from,created_at)
 values(oid,v,'original','synthetic-original','synthetic-revision','sha256:'||repeat('c',64),original_key,false,'{}',now());
 insert into public.source_representations(representation_id,source_version_id,kind,provider_id,provider_revision,content_sha256,object_key,lossy,derived_from,created_at)
 values(pid,v,'normalized','synthetic-cdr','synthetic-revision','sha256:'||repeat('d',64),pdf_key,true,array[oid],now());
 insert into public.foundation_native_purpose_members(native_grant_id,intake_approval_id,intake_file_key,document_id,reservation_id,
  source_id,source_version_id,original_representation_id,normalized_representation_id,original_sha256,original_bytes,quarantine_original_key,
  normalized_pdf_key,normalized_pdf_sha256,security_receipt_id,security_object_key,security_object_sha256,security_qualification_id,
  security_attestation_sha256,native_object_key,native_object_sha256,native_bytes)
 values('90000000-0000-4000-8000-000000000092','90000000-0000-4000-8000-000000000091','synthetic-file-'||i,d,rid,
  d::text,v,oid,pid,'sha256:'||repeat('c',64),12,original_key,pdf_key,'sha256:'||repeat('d',64),'unverified-security-'||i,
  'quarantine/pilot-candidate/'||d::text||'/receipt','sha256:'||repeat('e',64),'unverified-security-profile','sha256:'||repeat('f',64),
  'immutable/pilot-candidate/pilot-candidate/'||d::text||'/'||repeat('c',64)||'/source.xlsx','sha256:'||repeat('c',64),12);
end;
$$;
select pg_temp.seed_candidate_member(91);
select pg_temp.seed_candidate_member(92);
create function pg_temp.candidate_context() returns jsonb language sql stable as $$
 select pg_catalog.jsonb_build_object('workspaceId',workspace_key,'tenantId',tenant_id,'principalUserId',principal_user_id,
  'jobId',job_id,'authorizationRevision',authorization_revision,'collectionId',collection_id,'replayBinding',replay_binding,
  'documentIds',pg_catalog.jsonb_build_array(pg_temp.candidate_doc(92)::text,pg_temp.candidate_doc(91)::text))
 from public.foundation_native_purpose_grants where native_grant_id='90000000-0000-4000-8000-000000000092';
$$;
-- New pinned-row predicate isolation: a TEMP projection with only the job key relevant to
-- `not exists`. It does NOT seed a canonical connector/security/qualification or bypass its FKs.
-- Real source-authority FK insertion/privilege and cross-session race remain separately UNRUN.
create temporary table native_candidate_new_source_authority(job_id text not null);
create function pg_temp.native_candidate_after_waits() returns void language plpgsql as $$
declare mode text:=pg_catalog.current_setting('tavonel.native_candidate_test_mode',true);
begin
 if mode='revoke_member' then
  update public.foundation_workspace_members set state='revoked',revoked_at=pg_catalog.clock_timestamp()
   where workspace_key='pilot-candidate' and user_id='88888888-8888-4888-8888-888888888891';
 elsif mode='change_epoch' then
  update public.foundation_workspace_members set role='admin',authorization_revision=authorization_revision+1
   where workspace_key='pilot-candidate' and user_id='88888888-8888-4888-8888-888888888891';
 elsif mode='new_source_authority' then
  insert into pg_temp.native_candidate_new_source_authority values('cjob-'||repeat('4',32));
 elsif mode='wrong_collection' then
  update public.foundation_native_purpose_grants set collection_id='collection-'||repeat('9',32)
   where native_grant_id='90000000-0000-4000-8000-000000000092';
 elsif mode='wrong_replay' then
  update public.foundation_native_purpose_grants set replay_binding='native-work-'||repeat('9',32)
   where native_grant_id='90000000-0000-4000-8000-000000000092';
 end if;
 -- A reader's generic error-to-null must not let a failed fixture mutation masquerade as
 -- policy refusal. Set this only AFTER the mutation succeeds; case wrapper asserts it.
 perform pg_catalog.set_config('tavonel.native_candidate_test_observed',coalesce(mode,'none'),true);
end;
$$;
do $$
declare definition text;
begin
 definition:=pg_catalog.pg_get_functiondef('public.read_foundation_native_purpose_candidate_v1(jsonb,uuid)'::regprocedure);
 if pg_catalog.strpos(definition,'current_member as materialized')=0 or pg_catalog.strpos(definition,'to_regprocedure')=0 then
  raise exception 'corrected reader prerequisite missing'; end if;
 definition:=pg_catalog.replace(definition,'public.read_foundation_native_purpose_candidate_v1','pg_temp.read_native_candidate_test');
 definition:=pg_catalog.replace(definition,'SECURITY DEFINER','SECURITY INVOKER');
 definition:=pg_catalog.replace(definition,'prerequisite_review_complete constant boolean := false','prerequisite_review_complete constant boolean := true');
 definition:=pg_catalog.replace(definition,'  -- ONE fresh, NON-LOCKING capture AFTER ALL waits.',
  '  perform pg_temp.native_candidate_after_waits();'||pg_catalog.chr(10)||'  -- ONE fresh, NON-LOCKING capture AFTER ALL waits.');
 definition:=pg_catalog.replace(definition,'public.foundation_compile_job_source_authority ja where ja.job_id=j.job_id',
  'pg_temp.native_candidate_new_source_authority ja where ja.job_id=j.job_id');
 execute definition;
 execute 'revoke all on function pg_temp.read_native_candidate_test(jsonb,uuid) from public,anon,authenticated,service_role';
end;
$$;
create function pg_temp.read_candidate_case(mode text default 'none') returns jsonb language plpgsql as $$
declare captured_result jsonb; context jsonb:=pg_temp.candidate_context();
begin
 begin
 perform pg_catalog.set_config('tavonel.native_candidate_test_mode',mode,true);
  perform pg_catalog.set_config('tavonel.native_candidate_test_observed','',true);
  if mode='wrong_collection' then context:=pg_catalog.jsonb_set(context,'{collectionId}',pg_catalog.to_jsonb('collection-'||repeat('9',32))); end if;
  if mode='wrong_replay' then context:=pg_catalog.jsonb_set(context,'{replayBinding}',pg_catalog.to_jsonb('native-work-'||repeat('9',32))); end if;
  captured_result:=pg_temp.read_native_candidate_test(context,'90000000-0000-4000-8000-000000000092');
  if pg_catalog.current_setting('tavonel.native_candidate_test_observed',true) is distinct from mode then
   raise exception 'after-waits fixture hook failed or was not reached: %',mode; end if;
  if mode='revoke_member' and not exists(select 1 from public.foundation_workspace_members where workspace_key='pilot-candidate'
    and user_id='88888888-8888-4888-8888-888888888891' and state='revoked') then raise exception 'revocation fixture failed'; end if;
  if mode='change_epoch' and not exists(select 1 from public.foundation_workspace_members cm join public.foundation_compile_jobs j
    on j.workspace_key=cm.workspace_key and j.created_by_user_id=cm.user_id where j.job_id='cjob-'||repeat('4',32)
    and cm.authorization_revision<>j.authorization_revision) then raise exception 'epoch fixture failed'; end if;
  if mode='new_source_authority' and not exists(select 1 from pg_temp.native_candidate_new_source_authority
    where job_id='cjob-'||repeat('4',32)) then raise exception 'source-authority fixture failed'; end if;
  -- Roll back private hook changes without rolling back pgTAP assertion counters. PL/pgSQL
  -- variables retain their values when the enclosed subtransaction rolls back.
  raise exception using errcode='ZX091',message='rollback synthetic case';
 exception when sqlstate 'ZX091' then null;
 end;
 return captured_result;
end;
$$;
select ok((select collection_id is null from public.foundation_compile_jobs where job_id='cjob-'||repeat('4',32)),
 'healthy ordinary job has NULL pre-output collection_id');
select is(pg_temp.read_candidate_case()->>'kind','unverified_native_authority_candidate','positive pending candidate can return through temporary harness');
select is(pg_temp.read_candidate_case()->'qualification'->>'state','unreviewed','positive remains unreviewed, no qualification');
select is(pg_temp.read_candidate_case()->'grant'->>'state','proposed','positive remains proposed, no native permission');
select is(pg_catalog.jsonb_array_length(pg_temp.read_candidate_case()->'members'),2,'positive preserves complete two-document set');
select ok((select pg_catalog.bool_and(value->>'bindingState'='unbound' and value->'signedProcessingReceipt'='null'::jsonb)
 from pg_catalog.jsonb_array_elements(pg_temp.read_candidate_case()->'members')),'positive has no fabricated output');
select is(pg_temp.read_candidate_case('revoke_member'),null::jsonb,'membership revoked AFTER helper/lock waits refuses fresh capture');
select is(pg_temp.read_candidate_case('change_epoch'),null::jsonb,'membership epoch changed AFTER helper/lock waits refuses fresh capture');
select is(pg_temp.read_candidate_case('new_source_authority'),null::jsonb,'new pinned row visible only at final capture refuses direct upload');
select is(pg_temp.read_candidate_case('wrong_collection'),null::jsonb,'matching wrong grant/context collection still fails immutable job derivation');
select is(pg_temp.read_candidate_case('wrong_replay'),null::jsonb,'matching wrong grant/context replay still fails immutable job derivation');
-- Same-name/different-arity existence cannot satisfy the exact six-argument prerequisite.
create function pg_temp.synthetic_authorizer(text) returns boolean language sql immutable as $$ select true $$;
do $$
declare definition text;
begin
 definition:=pg_catalog.pg_get_functiondef('pg_temp.read_native_candidate_test(jsonb,uuid)'::regprocedure);
 -- pg_get_functiondef emits the physical pg_temp_N schema, not the pg_temp alias.
 definition:=pg_catalog.regexp_replace(definition,'^CREATE OR REPLACE FUNCTION [^(]+',
  'CREATE OR REPLACE FUNCTION pg_temp.read_missing_prerequisite_test');
 definition:=pg_catalog.replace(definition,'public.authorize_foundation_compile_job','pg_temp.synthetic_authorizer');
 execute definition;
 execute 'revoke all on function pg_temp.read_missing_prerequisite_test(jsonb,uuid) from public,anon,authenticated,service_role';
end;
$$;
select ok(pg_catalog.to_regprocedure('pg_temp.synthetic_authorizer(text)') is not null,'other arity exists');
select is(pg_temp.read_missing_prerequisite_test(pg_temp.candidate_context(),'90000000-0000-4000-8000-000000000092'),
 null::jsonb,'missing exact six-argument helper refuses despite another overload');
select ok(pg_catalog.strpos(pg_catalog.pg_get_functiondef('public.read_foundation_native_purpose_candidate_v1(jsonb,uuid)'::regprocedure),
 'prerequisite_review_complete constant boolean := false')>0,'temporary tests leave public runtime gate unchanged');
select * from finish();
rollback;

-- REAL TWO-SESSION ACCEPTANCE SCENARIOS, UNRUN. Use this seed in a separately approved
-- disposable fixture setup (do not reuse its outer rollback transaction as a concurrency run):
-- A. Hold source/version row in session B; start temp reader A so early helper succeeds and A
--    waits; revoke member or increment epoch in B, COMMIT; A must return null after capture.
-- B. After A's early helper, insert a REAL FK-valid foundation_compile_job_source_authority row
--    for that job in B; COMMIT while A waits; A must refuse even without requested connector rows.
-- C. Single-document deletion B first holds doc 92 deletion lock; A multi-doc reader holds doc
--    91 and waits for doc 92; B acquires workspace intake/legal hold and commits. A proceeds or
--    refuses due deletion; it must not deadlock. Old per-document helper looping held workspace
--    lock before waiting for doc 92 and formed the opposite wait cycle. Repeat reversed IDs.
-- D. Verify missing exact overload returns null despite a same-name different overload; global
--    mode refuses; original gate stays false; no ordinary client role can invoke temp harness.
