#!/usr/bin/env node
// Real-input end-to-end proving harness for the TAVONEL public v1 API.
//
// Every path below was read out of the site repo, not assumed. Two of them are
// deliberately NOT under /api/v1 because no v1 route exists (see GAPS.md), and
// the chain stops at promotion because promotion has no API-key route at all.
//
// Node 22. No dependencies: global fetch, node:crypto, node:fs.
//
// -----------------------------------------------------------------------------
// This is the growth-campaign copy (WG-032/033/055, 2026-09-11), taken verbatim
// from D:\CodexProjects\uskc-lanes\e2e\prove.mjs (2026-09-06) and extended. That
// original and its receipts are read-only evidence and were not modified.
//
// What is new here, and nothing else:
//   --plan                 the 18-step model and what each step would call, with no
//                          credential read and no call made.
//   EXTERNAL_CONSUMER      step 12: a read of the same active World from outside the
//   PACKAGE_DOWNLOAD       browser. Step 13: the signed package, plus the verdict of
//                          the package verifier that already ships to customers.
//   receipt.journey        the 18 steps with execution / semantic / task recorded
//                          together, from the same function the checker uses.
//   receipt.costAccounting measured: false. Nothing here measures cost, so nothing
//                          here writes a number for it.
//
// Steps 12 and 13 only run after ASK has succeeded, which needs a promoted World,
// which needs a person. Running this file cannot promote anything.
// -----------------------------------------------------------------------------

import { createHash } from "node:crypto";
import { readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { journeyFromReceipt, planLines, PACKAGE_CONTRACT } from "./acceptance-checker.mjs";
// The package validator that already exists here and ships to customers as
// public/developer/tavonel-verify-package.mjs. Standard library only, so importing it keeps this
// harness dependency-free, and step 13 gets the real verdict instead of a second implementation.
import { readPackage, validateCompiledWorldPackage } from "../compiled-world/validate.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
// The sample documents live with the 2026-09-06 harness and are regenerated by its
// make_fixtures.py. This copy carries none of its own, so the directory is an input.
const FIXTURE_DIR = process.env.E2E_FIXTURE_DIR ?? join(HERE, "fixtures");
const ORIGIN = (process.env.TAVONEL_ORIGIN ?? "https://tavonel.com").replace(/\/+$/, "");
const KEY = process.env.TAVONEL_API_KEY ?? "";
const PER_FILE_TIMEOUT_MS = Number(process.env.E2E_TIMEOUT_MS ?? 15 * 60 * 1000);
const POLL_MS = Number(process.env.E2E_POLL_MS ?? 5_000);

// name -> [file, declared mime, unique token, question]
const FIXTURES = {
  pdf: ["sample.pdf", "application/pdf", "TAVONEL-E2E-PDF-7f3a", "What is the audit token for this document?"],
  docx: ["sample.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "TAVONEL-E2E-DOCX-7f3a", "What is the audit token for this document?"],
  xlsx: ["sample.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "TAVONEL-E2E-XLSX-7f3a", "What is the audit token in the calibration sheet?"],
  pptx: ["sample.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "TAVONEL-E2E-PPTX-7f3a", "What is the audit token for this deck?"],
  png: ["sample.png", "image/png", "TAVONEL-E2E-PNG-7f3a", "What is the audit token for this image?"],
  // Image-only A4 page (Pillow, 200 dpi): the scanned-PDF path, which the hand-written text PDF does not exercise.
  pdfscan: ["sample_scan.pdf", "application/pdf", "TAVONEL-E2E-PDF-7f3a", "What is the audit token for this document?"],
};
// A re-upload of identical bytes is the same source version to the worker, so a version that already has an
// OCR review record stays in review. E2E_SALT changes the token (and so the bytes) when make_fixtures.py is
// run with the same salt, giving a fresh version instead of a replay.
const SALT = process.env.E2E_SALT ?? "";
for (const row of Object.values(FIXTURES)) row[2] += SALT;

// The chain, in order. A verdict names the step it stopped at.
const STEPS = [
  "CAPABILITIES",
  "UPLOAD_CAPABILITY",
  "R2_PUT",
  "CONFIRM",
  "DOCUMENT_TERMINAL",
  "COMPILE_JOB",
  "COMPILE_TERMINAL",
  "COLLECTION",
  "WORLD",
  "ASK",
  // Steps 12 and 13 of the 18-step model. Both are reads of a World that is already
  // active, so neither can run before a person has promoted the candidate.
  "EXTERNAL_CONSUMER",
  "PACKAGE_DOWNLOAD",
];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * One recorded HTTP call. Body is parsed as JSON when it is JSON, kept verbatim otherwise.
 *
 * `raw: true` leaves the response body unread, for the one call whose body is an archive: reading
 * it as text here would both mangle it and consume the stream the caller needs.
 */
async function call(log, step, method, url, { json, headers = {}, body, auth = true, raw = false } = {}) {
  const started = performance.now();
  const init = { method, headers: { ...headers } };
  if (auth && KEY) init.headers.authorization = `Bearer ${KEY}`;
  if (json !== undefined) {
    init.headers["content-type"] = "application/json";
    init.body = JSON.stringify(json);
  } else if (body !== undefined) {
    init.body = body;
  }
  let res, text, err = null;
  try {
    res = await fetch(url, init);
    if (!raw) text = await res.text();
  } catch (e) {
    err = String(e?.message ?? e);
  }
  const latencyMs = Math.round(performance.now() - started);
  let parsed = null;
  if (text) { try { parsed = JSON.parse(text); } catch { parsed = null; } }
  const entry = {
    step,
    method,
    // R2 PUT URLs carry a presigned signature; the path is recorded, the query is not.
    path: url.startsWith(ORIGIN) ? url.slice(ORIGIN.length) : `${new URL(url).origin}${new URL(url).pathname} (presigned query redacted)`,
    status: res?.status ?? null,
    code: parsed?.code ?? null,
    latencyMs,
    ...(err ? { transportError: err } : {}),
  };
  log.push(entry);
  return { res, parsed, text, entry };
}

function verdict(reached, failedAt) {
  if (failedAt) return `FAILED_${failedAt}`;
  if (reached === "ASK") return "PROVEN_E2E";
  return `REACHED_${reached}`;
}

async function proveOne(format, capabilities) {
  const [filename, mime, token, question] = FIXTURES[format];
  const path = join(FIXTURE_DIR, filename);
  const bytes = readFileSync(path);
  const deadline = Date.now() + PER_FILE_TIMEOUT_MS;
  const calls = [];
  const receipt = {
    origin: ORIGIN,
    format,
    fileName: filename,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.length,
    declaredMimeType: mime,
    uniqueToken: token,
    question,
    startedAt: new Date().toISOString(),
    capability: capabilities?.manifest?.entries?.find((e) => e.mime === mime) ?? null,
    capabilityManifestSha256: capabilities?.manifest?.contentSha256 ?? null,
    // Recorded rather than assumed: this route is absent from some deployments.
    capabilityLookup: capabilities?.status === 200
      ? "GET /api/v1/capabilities 200"
      : `GET /api/v1/capabilities ${capabilities?.status ?? "unreachable"} -- capability status unavailable from the API`,
    calls,
    documentId: null,
    documentProcessingState: null,
    compileJobId: null,
    compileJobState: null,
    collectionId: null,
    readerRouteLabel: null,
    evidenceLocators: null,
    tokenFoundInEvidence: null,
    blockedBy: null,
  };
  let reached = "CAPABILITIES";
  let failedAt = null;

  try {
    // 1. Admission -> presigned browser-direct R2 PUT.
    const cap = await call(calls, "UPLOAD_CAPABILITY", "POST", `${ORIGIN}/api/v1/uploads/capability`, {
      json: { originalFilename: filename, declaredMimeType: mime, requestedBytes: bytes.length },
    });
    if (cap.res?.status !== 200 || cap.parsed?.code !== "QUALIFIED") throw { at: "UPLOAD_CAPABILITY" };
    receipt.documentId = cap.parsed.documentId;
    reached = "UPLOAD_CAPABILITY";

    // 2. The bytes go straight to the bucket. Only content-type is signed.
    const put = await call(calls, "R2_PUT", "PUT", cap.parsed.uploadUrl, {
      headers: { "content-type": mime },
      body: bytes,
      auth: false,
    });
    if (!put.res?.ok) throw { at: "R2_PUT" };
    reached = "R2_PUT";

    // 3. Confirmation. No /api/v1 route exists for this -- see GAPS.md.
    const confirm = await call(calls, "CONFIRM", "POST", `${ORIGIN}/api/uploads/confirm`, {
      json: { documentId: receipt.documentId },
    });
    if (confirm.res?.status !== 200 || confirm.parsed?.code !== "UPLOAD_CONFIRMED") throw { at: "CONFIRM" };
    reached = "CONFIRM";

    // 4. CDR/OCR. The document appears in the inventory once sanitized; terminal is
    //    ocr_ready (readable) or operator_review (a human is required).
    let doc = null;
    while (Date.now() < deadline) {
      const list = await call(calls, "DOCUMENT_TERMINAL", "GET", `${ORIGIN}/api/v1/documents`);
      if (list.res?.status !== 200) throw { at: "DOCUMENT_TERMINAL" };
      doc = (list.parsed.documents ?? []).find((d) => d.documentId === receipt.documentId) ?? null;
      if (doc && doc.processingState !== "sanitized") break;
      doc = null;
      await sleep(POLL_MS);
    }
    if (!doc) { receipt.blockedBy = "TIMEOUT_WAITING_FOR_DOCUMENT_TERMINAL_STATE"; throw { at: "DOCUMENT_TERMINAL" }; }
    receipt.documentProcessingState = doc.processingState;
    receipt.documentInventoryRow = doc;
    reached = "DOCUMENT_TERMINAL";
    if (doc.processingState === "operator_review") {
      receipt.blockedBy = `OPERATOR_REVIEW_REQUIRED:${doc.ocrReviewReasonCode ?? "unspecified"}`;
      return finish(receipt, reached, null);
    }

    // 5. Durable compile. Also outside /api/v1 -- see GAPS.md.
    const job = await call(calls, "COMPILE_JOB", "POST", `${ORIGIN}/api/compile-jobs`, {
      json: { documentIds: [receipt.documentId] },
    });
    if (job.res?.status !== 202 || !job.parsed?.jobId) throw { at: "COMPILE_JOB" };
    receipt.compileJobId = job.parsed.jobId;
    reached = "COMPILE_JOB";

    let state = null;
    while (Date.now() < deadline) {
      const got = await call(calls, "COMPILE_TERMINAL", "GET", `${ORIGIN}/api/compile-jobs/${receipt.compileJobId}`);
      if (got.res?.status !== 200) throw { at: "COMPILE_TERMINAL" };
      state = got.parsed.job;
      if (["ready", "failed", "cancelled"].includes(state.state)) break;
      await sleep(POLL_MS);
    }
    receipt.compileJobState = state?.state ?? null;
    receipt.compileJob = state;
    if (state?.state !== "ready") {
      receipt.blockedBy = `COMPILE_NOT_READY:${state?.state ?? "timeout"}${state?.errorCode ? `:${state.errorCode}` : ""}`;
      throw { at: "COMPILE_TERMINAL" };
    }
    receipt.collectionId = state.collectionId;
    reached = "COMPILE_TERMINAL";

    // 6. The candidate package.
    const coll = await call(calls, "COLLECTION", "GET", `${ORIGIN}/api/v1/collections/${receipt.collectionId}`);
    if (coll.res?.status !== 200) throw { at: "COLLECTION" };
    receipt.collection = coll.parsed;
    receipt.readerRouteLabel = coll.parsed?.coreExecution?.runtime ?? coll.parsed?.artifact?.coreExecution?.runtime ?? null;
    reached = "COLLECTION";

    // 7-8. World + ask. Shared with --resume: after the founder promotes in the
    //      browser, that is the only part worth running again.
    return finish(receipt, ...(await worldAndAsk(receipt, calls, "COLLECTION")));
  } catch (e) {
    if (e?.at) return finish(receipt, reached, e.at);
    receipt.harnessError = String(e?.stack ?? e);
    return finish(receipt, reached, reached);
  }
  return finish(receipt, reached, failedAt);
}

/**
 * The active world, then the grounded ask. Mutates `receipt`; returns
 * `[reachedStep, failedStep|null]` for `finish`.
 *
 * Promotion is browser-session-only, so on a run that has not been promoted this
 * stops at WORLD with ACTIVE_WORLD_NOT_FOUND. That is the designed refusal, not a
 * failure, and it is what --resume exists to pick up after.
 */
async function worldAndAsk(receipt, calls, reached) {
  const world = await call(calls, "WORLD", "GET", `${ORIGIN}/api/v1/collections/${receipt.collectionId}/world`);
  if (world.res?.status !== 200) {
    receipt.blockedBy = world.parsed?.code === "ACTIVE_WORLD_NOT_FOUND"
      ? "PROMOTION_IS_BROWSER_SESSION_ONLY (no API-key route to POST /api/collections/{id}/promote)"
      : `WORLD_UNAVAILABLE:${world.parsed?.code ?? world.res?.status}`;
    return [reached, null];
  }
  receipt.activeWorld = world.parsed.activeWorld;
  reached = "WORLD";

  const ask = await call(calls, "ASK", "POST", `${ORIGIN}/api/v1/collections/${receipt.collectionId}/ask`, {
    json: { question: receipt.question },
  });
  // The raw response is kept whatever happened, so a refusal is inspectable.
  receipt.askResponse = ask.parsed ?? ask.text ?? null;
  if (ask.res?.status !== 200) {
    receipt.blockedBy = `ASK_REFUSED:${ask.parsed?.code ?? ask.res?.status}`;
    return [reached, "ASK"];
  }
  receipt.readerRouteLabel = ask.parsed.retrievalPath ?? receipt.readerRouteLabel;
  // Verbatim, both shapes: the compiled pipeline answers with a ContextPacket, the
  // fallback with citations. Neither is normalized here.
  receipt.evidenceLocators = ask.parsed.contextPacket ?? ask.parsed.citations ?? null;
  receipt.tokenFoundInEvidence = JSON.stringify(receipt.evidenceLocators ?? {}).includes(receipt.uniqueToken);
  if (ask.parsed.code !== "GROUNDED_ANSWER") {
    receipt.blockedBy = `ANSWER_ABSTAINED:${ask.parsed.reason ?? "no reason given"}`;
    return [reached, null];
  }
  // PROVEN_E2E means the file's own token came back inside the evidence. A grounded
  // answer that cites something else proves retrieval ran, not that this file was read.
  if (!receipt.tokenFoundInEvidence) {
    receipt.blockedBy = `TOKEN_NOT_IN_EVIDENCE:${receipt.uniqueToken}`;
    return [reached, null];
  }
  // The grounded answer is J1. Steps 12 and 13 are J2: the same World read by something
  // that is not this browser, and the same World carried away as a file. Both are reads,
  // both need the World that already exists by this line, and neither changes the verdict --
  // PROVEN_E2E stays a statement about the answer and its evidence.
  await consumeExternally(receipt, calls);
  await consumeAsFile(receipt, calls);
  return ["ASK", null];
}

/**
 * Step 12. `POST /api/v1/collections/{id}/search` takes the same `ask:read` scope as /ask, so a
 * key-holding consumer outside the browser -- an agent, a CLI, the MCP server in
 * public/developer/tavonel-mcp.mjs -- reads the same World through the same tenant boundary.
 * Recorded as a failure to consume, never as a failure of the answer.
 */
async function consumeExternally(receipt, calls) {
  const via = `POST /api/v1/collections/{id}/search (Bearer API key, not a browser session)`;
  const search = await call(calls, "EXTERNAL_CONSUMER", "POST", `${ORIGIN}/api/v1/collections/${receipt.collectionId}/search`, {
    json: { query: receipt.uniqueToken, limit: 5 },
  });
  receipt.externalConsumer = {
    via,
    status: search.res?.status ?? null,
    code: search.parsed?.code ?? null,
    tokenFoundInResults: search.res?.status === 200 ? JSON.stringify(search.parsed ?? {}).includes(receipt.uniqueToken) : null,
  };
}

/**
 * Step 13. Download the signed package, save it, and let the validator that already ships to
 * customers judge it. Then check the paths a cookbook's "output" section may promise
 * (PACKAGE_CONTRACT) -- the validator requires the compiled files but treats README.md,
 * AGENTS.md and manifest/ai-entrypoint.json as merely allowed, because an artifact that never
 * became a download has none of them. A customer download must have all three.
 *
 * `verified` stays null when the validator could not be run. It is never assumed true.
 */
async function consumeAsFile(receipt, calls) {
  const via = "GET /api/v1/collections/{id}/download";
  const got = await call(calls, "PACKAGE_DOWNLOAD", "GET", `${ORIGIN}/api/v1/collections/${receipt.collectionId}/download`, { raw: true });
  const pkg = { via, status: got.res?.status ?? null, bytes: null, sha256: null, savedTo: null, verifier: null, verified: null, missingContractPaths: null, verifyCommand: null };
  receipt.filePackage = pkg;
  if (got.res?.status !== 200) return;

  const bytes = Buffer.from(await got.res.arrayBuffer().catch(() => new ArrayBuffer(0)));
  if (!bytes.length) { pkg.verifier = "download returned 200 with no bytes"; return; }
  const dir = join(HERE, "receipts");
  mkdirSync(dir, { recursive: true });
  pkg.savedTo = join(dir, `${receipt.format}_package_${receipt.collectionId}.zip`);
  writeFileSync(pkg.savedTo, bytes);
  pkg.bytes = bytes.length;
  pkg.sha256 = createHash("sha256").update(bytes).digest("hex");
  // The command a customer runs on the same file, printed so the receipt is reproducible by hand.
  pkg.verifyCommand = `node public/developer/tavonel-verify-package.mjs --package "${pkg.savedTo}" --require-signature --json`;

  try {
    const read = await readPackage(pkg.savedTo);
    const report = validateCompiledWorldPackage(read.files, { requireSignature: true, lifecycle: read.artifact?.lifecycle });
    pkg.verified = report.ok === true;
    pkg.verifier = `validate.mjs ok=${report.ok}, ${read.files.size} files, ${report.errors.length} errors`;
    pkg.missingContractPaths = PACKAGE_CONTRACT.filter((p) => !read.files.has(p));
  } catch (e) {
    pkg.verified = null;
    pkg.verifier = `package could not be read: ${String(e?.message ?? e).slice(0, 200)}`;
  }
}

function finish(receipt, reached, failedAt) {
  receipt.finishedAt = new Date().toISOString();
  receipt.reachedStep = reached;
  receipt.stepChain = STEPS;
  receipt.verdict = verdict(reached, failedAt);
  // Step 18. Time and failure are recorded per call; cost is not instrumented anywhere in this
  // pipeline, so the field says so and carries no number. An estimate here would be a fabrication.
  receipt.costAccounting = {
    measured: false,
    reason: "no GPU, token or dollar cost is exposed on any route this harness calls; per-run cost needs product-side instrumentation that does not exist yet",
    currency: null,
    amount: null,
  };
  // The 18-step table, from the same function the checker uses, so a receipt and a later
  // re-check of that receipt cannot disagree.
  receipt.journey = journeyFromReceipt(receipt);
  return receipt;
}

function writeReceipt(name, receipt) {
  const dir = join(HERE, "receipts");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, name);
  writeFileSync(file, JSON.stringify(receipt, null, 2));
  return file;
}

/**
 * The page the founder promotes on. `app/workspace/page.tsx` calls
 * POST /api/collections/{id}/promote and reads `?collection=` and `?job=` back out
 * of the URL on load, so this deep link lands on the right candidate.
 */
function promoteUrl(collectionId, jobId) {
  const url = new URL(`${ORIGIN}/workspace`);
  url.searchParams.set("collection", collectionId);
  if (jobId) url.searchParams.set("job", jobId);
  return url.toString();
}

function printPromotionHint(receipt, receiptFile) {
  if (!receipt.collectionId) return;
  console.log(`
  Promotion is browser-session-only. To close the loop:
    1. open   ${promoteUrl(receipt.collectionId, receipt.compileJobId)}
    2. sign in, review the candidate and promote it
    3. run    node prove.mjs --resume "${receiptFile}"
  collectionId: ${receipt.collectionId}`);
}

/**
 * Re-run world + ask against an already-compiled collection, after a human promoted
 * it. Writes a NEW receipt beside the original; the original is never touched.
 */
async function resume({ receiptPath, collectionId, format }) {
  let prior = null;
  if (receiptPath) {
    prior = JSON.parse(readFileSync(receiptPath, "utf8"));
    collectionId ??= prior.collectionId;
    format ??= prior.format;
  }
  if (!collectionId) { console.error("no collectionId: pass --resume <receipt.json> or --collection <id>"); process.exit(2); }
  if (!FIXTURES[format]) { console.error(`--format must be one of ${Object.keys(FIXTURES).join(", ")}`); process.exit(2); }
  const [filename, mime, token, question] = FIXTURES[format];

  const calls = [];
  const receipt = {
    ...(prior ?? {}),
    origin: ORIGIN,
    format,
    fileName: filename,
    declaredMimeType: mime,
    uniqueToken: token,
    question,
    collectionId,
    mode: "resume",
    resumedFrom: receiptPath ?? null,
    priorVerdict: prior?.verdict ?? null,
    // The resume run's own calls only. The original receipt keeps the upload/compile ones.
    calls,
    startedAt: new Date().toISOString(),
    evidenceLocators: null,
    tokenFoundInEvidence: null,
    blockedBy: null,
  };

  const coll = await call(calls, "COLLECTION", "GET", `${ORIGIN}/api/v1/collections/${collectionId}`);
  if (coll.res?.status !== 200) return finish(receipt, "COMPILE_TERMINAL", "COLLECTION");
  receipt.collection = coll.parsed;
  receipt.readerRouteLabel = coll.parsed?.coreExecution?.runtime ?? coll.parsed?.artifact?.coreExecution?.runtime ?? null;
  return finish(receipt, ...(await worldAndAsk(receipt, calls, "COLLECTION")));
}

/** No key at all: prove the surface refuses, and that /capabilities deliberately does not. */
async function unauthenticatedProbe() {
  const calls = [];
  const collection = `collection-${"0".repeat(32)}`;
  await call(calls, "CAPABILITIES", "GET", `${ORIGIN}/api/v1/capabilities`, { auth: false });
  await call(calls, "UPLOAD_CAPABILITY", "POST", `${ORIGIN}/api/v1/uploads/capability`, {
    auth: false, json: { originalFilename: "sample.pdf", declaredMimeType: "application/pdf", requestedBytes: 803 },
  });
  await call(calls, "CONFIRM", "POST", `${ORIGIN}/api/uploads/confirm`, {
    auth: false, json: { documentId: "00000000-0000-4000-8000-000000000000" },
  });
  await call(calls, "DOCUMENT_TERMINAL", "GET", `${ORIGIN}/api/v1/documents`, { auth: false });
  await call(calls, "COMPILE_JOB", "POST", `${ORIGIN}/api/compile-jobs`, {
    auth: false, json: { documentIds: ["00000000-0000-4000-8000-000000000000"] },
  });
  await call(calls, "COLLECTION", "GET", `${ORIGIN}/api/v1/collections/${collection}`, { auth: false });
  await call(calls, "WORLD", "GET", `${ORIGIN}/api/v1/collections/${collection}/world`, { auth: false });
  await call(calls, "ASK", "POST", `${ORIGIN}/api/v1/collections/${collection}/ask`, {
    auth: false, json: { question: "What is the audit token for this document?" },
  });

  const guarded = calls.filter((c) => c.step !== "CAPABILITIES");
  return {
    origin: ORIGIN,
    ranAt: new Date().toISOString(),
    note: "No Authorization header sent. Every route that carries tenant data must refuse. /api/v1/capabilities is unauthenticated by design, so it is reported separately and does not decide the verdict.",
    calls,
    capabilitiesStatus: calls[0].status,
    capabilitiesPublic: calls[0].status === 200,
    allGuardedRoutesRefused: guarded.every((c) => c.status === 401 || c.status === 403),
    guardedStatuses: Object.fromEntries(guarded.map((c) => [c.path, `${c.status} ${c.code ?? ""}`.trim()])),
    verdict: guarded.every((c) => c.status === 401 || c.status === 403)
      ? "UNAUTHENTICATED_SURFACE_REFUSES"
      : "UNAUTHENTICATED_SURFACE_UNEXPECTED",
  };
}

async function main() {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  // Before anything can read an environment variable: what a real run would do, step by step.
  // No credential, no network, no file written. This is the mode to hand somebody who is
  // deciding whether to authorise the run.
  if (process.argv.includes("--plan")) {
    console.log(`Full-journey plan for ${ORIGIN}. No credential is read and no call is made.\n`);
    console.log(planLines().join("\n"));
    console.log(`\n  step 13 package contract:\n${PACKAGE_CONTRACT.map((p) => `    ${p}`).join("\n")}`);
    console.log(`\n  formats: ${Object.keys(FIXTURES).join(", ")}   fixtures: ${FIXTURE_DIR}`);
    console.log(`  receipts: ${join(HERE, "receipts")}`);
    console.log(`\n  what a real run needs, and this file cannot supply: docs/runbooks/full-journey-proof.md`);
    process.exit(0);
  }
  if (process.argv.includes("--probe") || !KEY) {
    if (!KEY && !process.argv.includes("--probe")) {
      console.error("TAVONEL_API_KEY is not set -- running the unauthenticated probe only.");
    }
    const probe = await unauthenticatedProbe();
    console.log(writeReceipt("unauthenticated_probe.json", probe));
    console.log(probe.verdict, JSON.stringify(probe.guardedStatuses, null, 2));
    process.exit(probe.verdict === "UNAUTHENTICATED_SURFACE_REFUSES" ? 0 : 1);
  }
  if (!KEY.startsWith("tvnl_live_")) {
    console.error("TAVONEL_API_KEY must be a tvnl_live_ key minted at /api/developer/keys.");
    process.exit(2);
  }

  const arg = (flag) => {
    const i = process.argv.indexOf(flag);
    return i > -1 ? process.argv[i + 1] : undefined;
  };
  if (process.argv.includes("--resume") || process.argv.includes("--collection")) {
    const receiptPath = arg("--resume");
    const receipt = await resume({ receiptPath, collectionId: arg("--collection"), format: arg("--format") });
    // Beside the original, never over it: a resume is a second measurement.
    const file = writeReceipt(`${receipt.format}_resume_${stamp}.json`, receipt);
    console.log(`${receipt.verdict}${receipt.blockedBy ? `  (${receipt.blockedBy})` : ""}\n${file}`);
    if (receipt.verdict !== "PROVEN_E2E" && receipt.blockedBy?.startsWith("PROMOTION_")) {
      printPromotionHint(receipt, receiptPath ?? file);
    }
    process.exit(receipt.verdict === "PROVEN_E2E" ? 0 : 1);
  }

  const capRes = await fetch(`${ORIGIN}/api/v1/capabilities`).catch(() => null);
  const capabilities = {
    status: capRes?.status ?? null,
    manifest: capRes?.ok ? await capRes.json() : null,
  };
  if (!capRes?.ok) console.error(`/api/v1/capabilities returned ${capRes?.status ?? "no response"} -- receipts will say so.`);

  const only = process.env.E2E_FORMATS?.split(",").map((s) => s.trim()).filter(Boolean);
  const formats = only?.length ? only : Object.keys(FIXTURES);
  const summary = [];
  for (const format of formats) {
    if (!FIXTURES[format]) { console.error(`unknown format ${format}`); continue; }
    if (!existsSync(join(FIXTURE_DIR, FIXTURES[format][0]))) {
      console.error(`missing fixture for ${format} in ${FIXTURE_DIR}; run make_fixtures.py or set E2E_FIXTURE_DIR`);
      continue;
    }
    const receipt = await proveOne(format, capabilities);
    const file = writeReceipt(`${format}_${stamp}.json`, receipt);
    summary.push({
      format, verdict: receipt.verdict, blockedBy: receipt.blockedBy, file,
      collectionId: receipt.collectionId,
      ...(receipt.collectionId ? { promoteUrl: promoteUrl(receipt.collectionId, receipt.compileJobId), resumeCommand: `node prove.mjs --resume "${file}"` } : {}),
    });
    console.log(`${format.padEnd(5)} ${receipt.verdict}${receipt.blockedBy ? `  (${receipt.blockedBy})` : ""}`);
    if (receipt.verdict !== "PROVEN_E2E" && receipt.collectionId) printPromotionHint(receipt, file);
  }
  writeReceipt(`summary_${stamp}.json`, { origin: ORIGIN, ranAt: stamp, stepChain: STEPS, results: summary });
  process.exit(summary.every((s) => s.verdict === "PROVEN_E2E") ? 0 : 1);
}

// Self-check: the verdict function is the only branching logic worth a test.
if (process.argv.includes("--self-test")) {
  const eq = (a, b) => { if (a !== b) throw new Error(`${a} !== ${b}`); };
  eq(verdict("ASK", null), "PROVEN_E2E");
  eq(verdict("COLLECTION", null), "REACHED_COLLECTION");
  eq(verdict("ASK", "ASK"), "FAILED_ASK");
  eq(verdict("CONFIRM", "DOCUMENT_TERMINAL"), "FAILED_DOCUMENT_TERMINAL");
  eq(verdict("WORLD", null), "REACHED_WORLD");
  eq(
    promoteUrl("collection-" + "a".repeat(32), "cjob-" + "b".repeat(32)),
    `${ORIGIN}/workspace?collection=collection-${"a".repeat(32)}&job=cjob-${"b".repeat(32)}`,
  );
  // A receipt that recorded nothing still has all 18 steps, and none of them may claim a pass.
  const empty = finish({ calls: [] }, "CAPABILITIES", null);
  eq(empty.journey.length, 18);
  eq(empty.journey.filter((r) => r.status === "PASS").length, 0);
  eq(empty.costAccounting.measured, false);
  eq(planLines().length, 18);
  console.log("self-test ok");
} else if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  // Entry guard (the pattern scripts/compiled-world/validate.mjs uses): importing this module
  // from a test must not fire a live run.
  await main();
}
