-- B15: durable, tenant-scoped workspace membership control plane.
--
-- This migration deliberately exposes no table or RPC to browser roles. The Next.js server
-- authenticates the session, while every mutation repeats authorization transactionally here.
-- Invitation bearer tokens are generated by the server and only their SHA-256 digests enter the
-- database. Email delivery is a separate external integration and is not performed here.
begin;

create table public.foundation_workspaces (
  workspace_key text primary key check (workspace_key ~ '^pilot-[A-Za-z0-9]{1,16}$'),
  display_name text not null check (char_length(display_name) between 1 and 120),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.foundation_workspace_members (
  workspace_key text not null references public.foundation_workspaces(workspace_key) on delete cascade,
  user_id uuid not null references auth.users(id) on delete restrict,
  role text not null check (role in ('owner', 'admin', 'member')),
  state text not null check (state in ('active', 'revoked')),
  invited_by uuid references auth.users(id) on delete set null,
  invited_at timestamptz,
  accepted_at timestamptz,
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (workspace_key, user_id),
  check (
    (state = 'active' and accepted_at is not null and revoked_at is null)
    or (state = 'revoked' and revoked_at is not null)
  )
);
create unique index foundation_workspace_one_active_owner_idx
  on public.foundation_workspace_members (workspace_key)
  where role = 'owner' and state = 'active';
create index foundation_workspace_members_user_idx
  on public.foundation_workspace_members (user_id, state, workspace_key);

create table public.foundation_workspace_invitations (
  invite_id uuid primary key default gen_random_uuid(),
  workspace_key text not null references public.foundation_workspaces(workspace_key) on delete cascade,
  invitee_email text not null check (
    invitee_email = lower(btrim(invitee_email))
    and char_length(invitee_email) between 3 and 320
    and invitee_email like '%_@_%._%'
  ),
  role text not null check (role in ('admin', 'member')),
  token_hash text not null unique check (token_hash ~ '^sha256:[a-f0-9]{64}$'),
  idempotency_key text not null check (idempotency_key ~ '^[A-Za-z0-9_-]{16,128}$'),
  state text not null default 'pending' check (state in ('pending', 'accepted', 'revoked', 'expired')),
  invited_by uuid not null references auth.users(id) on delete restrict,
  accepted_by uuid references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  revoked_at timestamptz,
  unique (workspace_key, invited_by, idempotency_key),
  check (expires_at > created_at),
  check (
    (state = 'pending' and accepted_by is null and accepted_at is null and revoked_at is null)
    or (state = 'accepted' and accepted_by is not null and accepted_at is not null and revoked_at is null)
    or (state = 'revoked' and revoked_at is not null)
    or (state = 'expired' and accepted_by is null and accepted_at is null)
  )
);
create index foundation_workspace_invites_lookup_idx
  on public.foundation_workspace_invitations (workspace_key, state, expires_at);

create table public.foundation_workspace_membership_events (
  event_id bigint generated always as identity primary key,
  workspace_key text not null references public.foundation_workspaces(workspace_key) on delete restrict,
  action text not null check (action in (
    'invite.created', 'invite.accepted', 'invite.revoked',
    'member.role_changed', 'member.revoked'
  )),
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  subject_user_id uuid references auth.users(id) on delete restrict,
  invite_id uuid references public.foundation_workspace_invitations(invite_id) on delete restrict,
  request_id text not null check (char_length(request_id) between 8 and 160),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  occurred_at timestamptz not null default clock_timestamp(),
  check (subject_user_id is not null or invite_id is not null)
);
create index foundation_workspace_membership_events_scope_idx
  on public.foundation_workspace_membership_events (workspace_key, occurred_at desc, event_id desc);

-- Preserve the existing opaque workspace keys exactly. A collision fails the migration via the
-- one-owner invariant rather than silently combining two tenants.
insert into public.foundation_workspaces (workspace_key, display_name, created_by)
select
  'pilot-' || left(regexp_replace(u.id::text, '[^A-Za-z0-9]', '', 'g'), 16),
  coalesce(nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''), 'Personal') || '''s workspace',
  u.id
from auth.users u;

insert into public.foundation_workspace_members (
  workspace_key, user_id, role, state, accepted_at
)
select
  'pilot-' || left(regexp_replace(u.id::text, '[^A-Za-z0-9]', '', 'g'), 16),
  u.id, 'owner', 'active', coalesce(u.created_at, now())
from auth.users u;

create or replace function public.create_foundation_workspace_invite(
  p_workspace_key text,
  p_actor_user_id uuid,
  p_invitee_email text,
  p_role text,
  p_token_hash text,
  p_idempotency_key text,
  p_expires_at timestamptz,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor public.foundation_workspace_members%rowtype;
  v_existing public.foundation_workspace_invitations%rowtype;
  v_invite public.foundation_workspace_invitations%rowtype;
  v_email text := lower(btrim(p_invitee_email));
begin
  if p_workspace_key !~ '^pilot-[A-Za-z0-9]{1,16}$'
    or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or char_length(v_email) > 320
    or p_role not in ('admin', 'member')
    or p_token_hash !~ '^sha256:[a-f0-9]{64}$'
    or p_idempotency_key !~ '^[A-Za-z0-9_-]{16,128}$'
    or p_expires_at <= clock_timestamp()
    or p_expires_at > clock_timestamp() + interval '30 days'
    or char_length(p_request_id) not between 8 and 160 then
    raise exception 'workspace_invite_input_invalid';
  end if;

  select * into v_actor from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_actor_user_id
   for update;
  if not found or v_actor.state <> 'active' or v_actor.role not in ('owner', 'admin') then
    raise exception 'workspace_invite_forbidden';
  end if;
  if v_actor.role = 'admin' and p_role <> 'member' then
    raise exception 'workspace_invite_role_forbidden';
  end if;

  select * into v_existing from public.foundation_workspace_invitations
   where workspace_key = p_workspace_key and invited_by = p_actor_user_id
     and idempotency_key = p_idempotency_key
   for update;
  if found then
    if v_existing.invitee_email <> v_email or v_existing.role <> p_role
      or v_existing.token_hash <> p_token_hash then
      raise exception 'workspace_invite_idempotency_conflict';
    end if;
    return jsonb_build_object(
      'inviteId', v_existing.invite_id, 'workspaceKey', v_existing.workspace_key,
      'email', v_existing.invitee_email, 'role', v_existing.role,
      'state', v_existing.state, 'expiresAt', v_existing.expires_at,
      'idempotentReplay', true
    );
  end if;

  if exists (
    select 1 from public.foundation_workspace_members m
     join auth.users u on u.id = m.user_id
    where m.workspace_key = p_workspace_key and m.state = 'active'
      and lower(u.email) = v_email
  ) then
    raise exception 'workspace_invite_already_member';
  end if;

  update public.foundation_workspace_invitations
     set state = 'expired'
   where workspace_key = p_workspace_key and invitee_email = v_email
     and state = 'pending' and expires_at <= clock_timestamp();
  if exists (
    select 1 from public.foundation_workspace_invitations
     where workspace_key = p_workspace_key and invitee_email = v_email
       and state = 'pending' and expires_at > clock_timestamp()
  ) then
    raise exception 'workspace_invite_pending';
  end if;

  insert into public.foundation_workspace_invitations (
    workspace_key, invitee_email, role, token_hash, idempotency_key,
    invited_by, expires_at
  ) values (
    p_workspace_key, v_email, p_role, p_token_hash, p_idempotency_key,
    p_actor_user_id, p_expires_at
  ) returning * into v_invite;

  insert into public.foundation_workspace_membership_events (
    workspace_key, action, actor_user_id, invite_id, request_id, details
  ) values (
    p_workspace_key, 'invite.created', p_actor_user_id, v_invite.invite_id,
    p_request_id, jsonb_build_object('email', v_email, 'role', p_role, 'expiresAt', p_expires_at)
  );
  return jsonb_build_object(
    'inviteId', v_invite.invite_id, 'workspaceKey', v_invite.workspace_key,
    'email', v_invite.invitee_email, 'role', v_invite.role,
    'state', v_invite.state, 'expiresAt', v_invite.expires_at,
    'idempotentReplay', false
  );
end;
$$;

create or replace function public.accept_foundation_workspace_invite(
  p_actor_user_id uuid,
  p_token_hash text,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_invite public.foundation_workspace_invitations%rowtype;
  v_email text;
begin
  if p_token_hash !~ '^sha256:[a-f0-9]{64}$'
    or char_length(p_request_id) not between 8 and 160 then
    raise exception 'workspace_invite_accept_input_invalid';
  end if;
  select lower(email) into v_email from auth.users where id = p_actor_user_id;
  if not found or v_email is null then raise exception 'workspace_invite_identity_invalid'; end if;

  select * into v_invite from public.foundation_workspace_invitations
   where token_hash = p_token_hash for update;
  if not found then raise exception 'workspace_invite_not_found'; end if;
  if v_invite.state = 'accepted' then
    if v_invite.accepted_by = p_actor_user_id and exists (
      select 1 from public.foundation_workspace_members
       where workspace_key = v_invite.workspace_key and user_id = p_actor_user_id and state = 'active'
    ) then
      return jsonb_build_object(
        'workspaceKey', v_invite.workspace_key, 'role', v_invite.role,
        'state', 'accepted', 'idempotentReplay', true
      );
    end if;
    raise exception 'workspace_invite_consumed';
  end if;
  if v_invite.state <> 'pending' then raise exception 'workspace_invite_not_active'; end if;
  if v_invite.expires_at <= clock_timestamp() then
    update public.foundation_workspace_invitations set state = 'expired'
     where invite_id = v_invite.invite_id;
    raise exception 'workspace_invite_expired';
  end if;
  if v_invite.invitee_email <> v_email then raise exception 'workspace_invite_identity_mismatch'; end if;

  insert into public.foundation_workspace_members (
    workspace_key, user_id, role, state, invited_by, invited_at, accepted_at, revoked_at, updated_at
  ) values (
    v_invite.workspace_key, p_actor_user_id, v_invite.role, 'active',
    v_invite.invited_by, v_invite.created_at, clock_timestamp(), null, clock_timestamp()
  )
  on conflict (workspace_key, user_id) do update set
    role = excluded.role, state = 'active', invited_by = excluded.invited_by,
    invited_at = excluded.invited_at, accepted_at = excluded.accepted_at,
    revoked_at = null, updated_at = excluded.updated_at
  where foundation_workspace_members.state = 'revoked';
  if not found then raise exception 'workspace_invite_member_conflict'; end if;

  update public.foundation_workspace_invitations
     set state = 'accepted', accepted_by = p_actor_user_id, accepted_at = clock_timestamp()
   where invite_id = v_invite.invite_id;
  insert into public.foundation_workspace_membership_events (
    workspace_key, action, actor_user_id, subject_user_id, invite_id, request_id, details
  ) values (
    v_invite.workspace_key, 'invite.accepted', p_actor_user_id, p_actor_user_id,
    v_invite.invite_id, p_request_id, jsonb_build_object('role', v_invite.role)
  );
  return jsonb_build_object(
    'workspaceKey', v_invite.workspace_key, 'role', v_invite.role,
    'state', 'accepted', 'idempotentReplay', false
  );
end;
$$;

create or replace function public.change_foundation_workspace_member_role(
  p_workspace_key text,
  p_actor_user_id uuid,
  p_subject_user_id uuid,
  p_role text,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor public.foundation_workspace_members%rowtype;
  v_subject public.foundation_workspace_members%rowtype;
begin
  if p_role not in ('admin', 'member') or char_length(p_request_id) not between 8 and 160 then
    raise exception 'workspace_member_role_input_invalid';
  end if;
  select * into v_actor from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_actor_user_id for update;
  if not found or v_actor.state <> 'active' or v_actor.role <> 'owner' then
    raise exception 'workspace_member_role_forbidden';
  end if;
  select * into v_subject from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_subject_user_id for update;
  if not found or v_subject.state <> 'active' then raise exception 'workspace_member_not_found'; end if;
  if v_subject.role = 'owner' then raise exception 'workspace_last_owner_protected'; end if;
  if v_subject.role = p_role then
    return jsonb_build_object('workspaceKey', p_workspace_key, 'userId', p_subject_user_id,
      'role', p_role, 'idempotentReplay', true);
  end if;
  update public.foundation_workspace_members set role = p_role, updated_at = clock_timestamp()
   where workspace_key = p_workspace_key and user_id = p_subject_user_id;
  insert into public.foundation_workspace_membership_events (
    workspace_key, action, actor_user_id, subject_user_id, request_id, details
  ) values (
    p_workspace_key, 'member.role_changed', p_actor_user_id, p_subject_user_id,
    p_request_id, jsonb_build_object('from', v_subject.role, 'to', p_role)
  );
  return jsonb_build_object('workspaceKey', p_workspace_key, 'userId', p_subject_user_id,
    'role', p_role, 'idempotentReplay', false);
end;
$$;

create or replace function public.revoke_foundation_workspace_member(
  p_workspace_key text,
  p_actor_user_id uuid,
  p_subject_user_id uuid,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor public.foundation_workspace_members%rowtype;
  v_subject public.foundation_workspace_members%rowtype;
begin
  if char_length(p_request_id) not between 8 and 160 then raise exception 'workspace_member_revoke_input_invalid'; end if;
  select * into v_actor from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_actor_user_id for update;
  if not found or v_actor.state <> 'active' or v_actor.role not in ('owner', 'admin') then
    raise exception 'workspace_member_revoke_forbidden';
  end if;
  select * into v_subject from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_subject_user_id for update;
  if not found then raise exception 'workspace_member_not_found'; end if;
  if v_subject.state = 'revoked' then
    return jsonb_build_object('workspaceKey', p_workspace_key, 'userId', p_subject_user_id,
      'state', 'revoked', 'idempotentReplay', true);
  end if;
  if v_subject.role = 'owner' then raise exception 'workspace_last_owner_protected'; end if;
  if v_actor.role = 'admin' and v_subject.role <> 'member' then raise exception 'workspace_member_revoke_forbidden'; end if;
  update public.foundation_workspace_members
     set state = 'revoked', revoked_at = clock_timestamp(), updated_at = clock_timestamp()
   where workspace_key = p_workspace_key and user_id = p_subject_user_id;
  insert into public.foundation_workspace_membership_events (
    workspace_key, action, actor_user_id, subject_user_id, request_id, details
  ) values (
    p_workspace_key, 'member.revoked', p_actor_user_id, p_subject_user_id,
    p_request_id, jsonb_build_object('role', v_subject.role)
  );
  return jsonb_build_object('workspaceKey', p_workspace_key, 'userId', p_subject_user_id,
    'state', 'revoked', 'idempotentReplay', false);
end;
$$;

create or replace function public.revoke_foundation_workspace_invite(
  p_workspace_key text,
  p_actor_user_id uuid,
  p_invite_id uuid,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor public.foundation_workspace_members%rowtype;
  v_invite public.foundation_workspace_invitations%rowtype;
begin
  if char_length(p_request_id) not between 8 and 160 then raise exception 'workspace_invite_revoke_input_invalid'; end if;
  select * into v_actor from public.foundation_workspace_members
   where workspace_key = p_workspace_key and user_id = p_actor_user_id for update;
  if not found or v_actor.state <> 'active' or v_actor.role not in ('owner', 'admin') then
    raise exception 'workspace_invite_revoke_forbidden';
  end if;
  select * into v_invite from public.foundation_workspace_invitations
   where workspace_key = p_workspace_key and invite_id = p_invite_id for update;
  if not found then raise exception 'workspace_invite_not_found'; end if;
  if v_invite.state = 'revoked' then
    return jsonb_build_object('inviteId', p_invite_id, 'state', 'revoked', 'idempotentReplay', true);
  end if;
  if v_invite.state <> 'pending' then raise exception 'workspace_invite_not_active'; end if;
  update public.foundation_workspace_invitations
     set state = 'revoked', revoked_at = clock_timestamp()
   where invite_id = p_invite_id;
  insert into public.foundation_workspace_membership_events (
    workspace_key, action, actor_user_id, invite_id, request_id, details
  ) values (p_workspace_key, 'invite.revoked', p_actor_user_id, p_invite_id, p_request_id, '{}'::jsonb);
  return jsonb_build_object('inviteId', p_invite_id, 'state', 'revoked', 'idempotentReplay', false);
end;
$$;

alter table public.foundation_workspaces enable row level security;
alter table public.foundation_workspace_members enable row level security;
alter table public.foundation_workspace_invitations enable row level security;
alter table public.foundation_workspace_membership_events enable row level security;

revoke all on public.foundation_workspaces, public.foundation_workspace_members,
  public.foundation_workspace_invitations, public.foundation_workspace_membership_events
  from public, anon, authenticated;
grant select, insert, update on public.foundation_workspaces, public.foundation_workspace_members,
  public.foundation_workspace_invitations to service_role;
grant select, insert on public.foundation_workspace_membership_events to service_role;
grant usage, select on sequence public.foundation_workspace_membership_events_event_id_seq to service_role;

revoke all on function public.create_foundation_workspace_invite(text, uuid, text, text, text, text, timestamptz, text),
  public.accept_foundation_workspace_invite(uuid, text, text),
  public.change_foundation_workspace_member_role(text, uuid, uuid, text, text),
  public.revoke_foundation_workspace_member(text, uuid, uuid, text),
  public.revoke_foundation_workspace_invite(text, uuid, uuid, text)
  from public, anon, authenticated;
grant execute on function public.create_foundation_workspace_invite(text, uuid, text, text, text, text, timestamptz, text),
  public.accept_foundation_workspace_invite(uuid, text, text),
  public.change_foundation_workspace_member_role(text, uuid, uuid, text, text),
  public.revoke_foundation_workspace_member(text, uuid, uuid, text),
  public.revoke_foundation_workspace_invite(text, uuid, uuid, text)
  to service_role;

-- Membership history is append-only even for the service role.
create or replace function public.prevent_foundation_membership_event_mutation()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  raise exception 'foundation_membership_events_append_only';
end;
$$;
create trigger foundation_membership_events_append_only
  before update or delete on public.foundation_workspace_membership_events
  for each row execute function public.prevent_foundation_membership_event_mutation();
revoke execute on function public.prevent_foundation_membership_event_mutation() from public, anon, authenticated;

commit;
